title: 'thierry rene web dev blog'
default_lang: en
author:
  name: 'Thierry Rene Matos'
  email: td_matos@terra.com.br
taxonomies:
  - webdev
  - frontend
  - backend
  - php
  - js
  - html
  - css
  - jquery
metadata:
  site-author: '@thierryrenemts'
  description: 'compartilhar é aprender'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
